"""initial

Revision ID: 07d2a9b9b729
Revises: 
Create Date: 2023-03-19 02:36:42.563417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d2a9b9b729'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('cpu', sa.String(length=128), nullable=False),
    sa.Column('gpu', sa.String(length=128), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk__project'))
    )
    op.create_table('consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('epoch_str', sa.String(length=128), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('co2', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name=op.f('fk__consumption__project_id__project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__consumption'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumption')
    op.drop_table('project')
    # ### end Alembic commands ###
