version: "3.8"

services:
  backend:
    build: .
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - ./.:/eco2ai_playground
    command:
      - /bin/sh
      - -c
      - |
        poetry run eco2ai-playground-db upgrade head
        poetry run eco2ai-playground-api
  postgres:
    image: "postgres:15.3-alpine3.18"
    env_file: .env
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
